### ISSUE TITLE
Change the hash function

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-hamt-ipld#6]
The current hash function used here (fnv.New128a) maps keys with the same prefix to hashes with the same prefix. This unnecessarily makes the tree much deeper than required.

**Comment by Kubuxu** [comment]
We were using murmur3 in case of HAMT in pb-unixfs, can you test it out.

**Comment by ianopolous** [comment]
Sure, @Kubuxu

**Comment by ianopolous** [comment]
murmur3 looks fine, and doesn't seem to show any noticeable slowdown. Shall I make a PR with that in as well?

**Comment by Kubuxu** [comment]
I would say yes.

@whyrusleeping what do you think?

**Comment by ianopolous** [comment]
done: https://github.com/ipfs/go-hamt-ipld/pull/7

**Comment by whyrusleeping** [comment]
SGTM. I just used fnv because i didnt feel like importing anything new at the time.
